FROM rust:bookworm AS builder

RUN apt-get update && apt-get install --no-install-recommends -y protobuf-compiler libprotobuf-dev pkg-config libssl-dev && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY Cargo.toml Cargo.lock ./
COPY build.rs ./
COPY .sqlx .sqlx/
COPY proto ./proto
COPY src ./src
COPY crates ./crates
COPY tests ./tests
COPY scenarios ./scenarios

ENV SQLX_OFFLINE=true

RUN cargo build --release --bin agent-executor

FROM debian:bookworm-slim

RUN apt-get update && apt-get install --no-install-recommends -y libssl-dev ca-certificates; \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY --from=builder /app/target/release/agent-executor .

ENTRYPOINT ["/app/agent-executor"]
