use assert_cmd::Command;
use predicates::prelude::*;
use std::fs;
use tempfile::TempDir;

fn stacker_cmd() -> Command {
    Command::cargo_bin("stacker-cli").expect("stacker-cli binary not found")
}

fn setup_project(dir: &TempDir, name: &str) {
    let config = format!(
        r#"
name: {name}
version: "1.0"
app:
  type: static
  path: "."
deploy:
  target: local
"#
    );

    fs::write(dir.path().join("stacker.yml"), config).expect("write stacker.yml");
    fs::write(dir.path().join("index.html"), "<h1>Hello</h1>").expect("write index.html");
}

#[test]
fn test_ci_export_bitbucket_generates_pipeline_file() {
    let dir = TempDir::new().expect("temp dir");
    setup_project(&dir, "bitbucket-app");

    stacker_cmd()
        .current_dir(dir.path())
        .args(["ci", "export", "--platform", "bitbucket"])
        .assert()
        .success()
        .stdout(predicate::str::contains("bitbucket-pipelines.yml"));

    let pipeline = fs::read_to_string(dir.path().join("bitbucket-pipelines.yml"))
        .expect("bitbucket pipeline should be written");
    assert!(pipeline.contains("Bitbucket Pipelines generated by Stacker for bitbucket-app"));
    assert!(pipeline.contains("stacker deploy --target local"));
    assert!(pipeline.contains("STACKER_TOKEN"));
}

#[test]
fn test_ci_validate_bitbucket_succeeds_for_generated_pipeline() {
    let dir = TempDir::new().expect("temp dir");
    setup_project(&dir, "validate-app");

    stacker_cmd()
        .current_dir(dir.path())
        .args(["ci", "export", "--platform", "bitbucket"])
        .assert()
        .success();

    stacker_cmd()
        .current_dir(dir.path())
        .args(["ci", "validate", "--platform", "bitbucket"])
        .assert()
        .success()
        .stdout(predicate::str::contains("looks up-to-date"));
}

#[test]
fn test_ci_export_bitbucket_alias_generates_pipeline_file() {
    let dir = TempDir::new().expect("temp dir");
    setup_project(&dir, "alias-app");

    stacker_cmd()
        .current_dir(dir.path())
        .args(["ci", "export", "--platform", "bb"])
        .assert()
        .success();

    assert!(dir.path().join("bitbucket-pipelines.yml").exists());
}

#[test]
fn test_ci_validate_bitbucket_alias_succeeds_for_generated_pipeline() {
    let dir = TempDir::new().expect("temp dir");
    setup_project(&dir, "alias-validate-app");

    stacker_cmd()
        .current_dir(dir.path())
        .args(["ci", "export", "--platform", "bitbucket-pipelines"])
        .assert()
        .success();

    stacker_cmd()
        .current_dir(dir.path())
        .args(["ci", "validate", "--platform", "bb"])
        .assert()
        .success()
        .stdout(predicate::str::contains("looks up-to-date"));
}

#[test]
fn test_ci_validate_bitbucket_fails_when_pipeline_file_missing() {
    let dir = TempDir::new().expect("temp dir");
    setup_project(&dir, "missing-pipeline-app");

    stacker_cmd()
        .current_dir(dir.path())
        .args(["ci", "validate", "--platform", "bitbucket"])
        .assert()
        .failure()
        .stderr(predicate::str::contains("Pipeline file not found"));
}

#[test]
fn test_ci_validate_bitbucket_fails_when_pipeline_is_stale() {
    let dir = TempDir::new().expect("temp dir");
    setup_project(&dir, "fresh-app");
    fs::write(
        dir.path().join("bitbucket-pipelines.yml"),
        "# Bitbucket Pipelines generated by Stacker for stale-app\npipelines:\n  branches:\n    main:\n      - step:\n          name: Deploy stale-app\n",
    )
    .expect("write stale pipeline");

    stacker_cmd()
        .current_dir(dir.path())
        .args(["ci", "validate", "--platform", "bitbucket"])
        .assert()
        .failure()
        .stderr(predicate::str::contains("out of sync"));
}

#[test]
fn test_ci_export_jenkins_generates_pipeline_file() {
    let dir = TempDir::new().expect("temp dir");
    setup_project(&dir, "jenkins-app");

    stacker_cmd()
        .current_dir(dir.path())
        .args(["ci", "export", "--platform", "jenkins"])
        .assert()
        .success()
        .stdout(predicate::str::contains("Jenkinsfile"));

    let pipeline =
        fs::read_to_string(dir.path().join("Jenkinsfile")).expect("Jenkinsfile should be written");
    assert!(pipeline.contains("Jenkins Pipeline generated by Stacker for jenkins-app"));
    assert!(pipeline.contains("stacker deploy --target local"));
    assert!(pipeline.contains("STACKER_TOKEN"));
}

#[test]
fn test_ci_validate_jenkins_succeeds_for_generated_pipeline() {
    let dir = TempDir::new().expect("temp dir");
    setup_project(&dir, "jenkins-validate-app");

    stacker_cmd()
        .current_dir(dir.path())
        .args(["ci", "export", "--platform", "jenkins"])
        .assert()
        .success();

    stacker_cmd()
        .current_dir(dir.path())
        .args(["ci", "validate", "--platform", "jenkins"])
        .assert()
        .success()
        .stdout(predicate::str::contains("looks up-to-date"));
}

#[test]
fn test_ci_export_unknown_platform_lists_bitbucket_in_supported_values() {
    let dir = TempDir::new().expect("temp dir");
    setup_project(&dir, "unknown-platform-app");

    stacker_cmd()
        .current_dir(dir.path())
        .args(["ci", "export", "--platform", "unknown"])
        .assert()
        .failure()
        .stderr(predicate::str::contains("bitbucket"))
        .stderr(predicate::str::contains("jenkins"));
}
